sudo: required

language: generic

branches:
  only:
  - master

services:
  - docker

env:
  # 1.0
  - DOCKER_TAG=1.0 AWS_CLI_VERSION=1.14.5 ECS_CLI_VERSION=1.0.0 EB_CLI_VERSION=3.14.2 S3_CMD_VERSION=2.0.1
  # 1.1
  - DOCKER_TAG=1.1 AWS_CLI_VERSION=1.14.5 ECS_CLI_VERSION=1.4.0 EB_CLI_VERSION=3.14.2 S3_CMD_VERSION=2.0.1
  # 1.2
  - DOCKER_TAG=1.2 AWS_CLI_VERSION=1.15.45 ECS_CLI_VERSION=1.6.0 EB_CLI_VERSION=3.14.2 S3_CMD_VERSION=2.0.1
  # latest
  - DOCKER_TAG=latest AWS_CLI_VERSION=1.15.45 ECS_CLI_VERSION=1.6.0 EB_CLI_VERSION=3.14.2 S3_CMD_VERSION=2.0.1

script:
  - bin/build.sh
  - bin/push.sh
